# Supabase Connection
[connections.supabase]
type = "sql"
url = "postgresql://postgres:Supabase14710!@db.maeistbokyjhewrrisvf.supabase.co:5432/postgres"
dialect = "postgresql"

# Replace these with your actual Supabase credentials
# These will be available in your Supabase project settings -> Database -> Connection string
database = "postgres"
host = "db.maeistbokyjhewrrisvf.supabase.co"
password = "Supabase14710!"
port = "5432"
username = "postgres"

# Other secrets
AWS_ACCESS_KEY_ID = "your-aws-access-key"
AWS_SECRET_ACCESS_KEY = "your-aws-secret-key"
AWS_DEFAULT_REGION = "your-aws-region"
S3_BUCKET_NAME = "your-s3-bucket"
GEMINI_API_KEY = "your-gemini-api-key"
QUARTR_API_KEY = "your-quartr-api-key" 